#!/bin/bash

# Examples: ./install_nginx path to /usr/share/nginx/html
# Installs epel-release
# Installs nginx
# Starts nginx
# Firewal passthru

# Install epel-release
echo "[Install Nginx] Installing epel-release"
sudo yum -y install epel-release

# Install Nginx
echo "[Install Nginx] Installing Nginx"
sudo yum -y install nginx

# Start Nginx
echo "[Install Nginx] Starting Nginx"
sudo systemctl start nginx

# Allow nginx through firewall
sudo firewall-cmd --permanent --zone=public --add-service=http
sudo firewall-cmd --permanent --zone=public --add-service=https
sudo firewall-cmd --permanent --zone=public --add-port=80/tcp 
sudo firewall-cmd --permanent --zone=public --add-port=80/udp
sudo firewall-cmd --reload

# Enable Nginx to start automatically in boot
sudo systemctl enable nginx

# Install done
echo "[Install Nginx] Done!"
